{
 "title": "Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ubuntu-Plex Data",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "\r\n<h1 style=\"color: #77216f; background-color: #dd4814; font-size: 45px; text-align: center;\">\r\nUbuntu-Plex Data\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ubuntu-Plex Data",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 0 },
   "options": {
    "content": "\r\n<h1 style=\"color: white; background-color: orange; font-size: 45px; text-align: center;\">\r\nProxmox Data\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ram Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes /1024 /1024 /1024",
     "legendFormat": "GB"
    }
   ]
  },
  {
   "title": "Pool Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "zfs_pool_health", "legendFormat": "{{pool}} " }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu))"
    }
   ]
  },
  {
   "title": "Ubuntu-Plex Data",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 3 },
   "options": {
    "content": "\r\n<h1 style=\"color: black; background-color: green; font-size: 20px; text-align: center;\">\r\nNvidia Quadro P2200\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Proxmox Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 /1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prox" }
     ]
    }
   ]
  },
  {
   "title": "Proxmox Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prox" }
     ]
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  },
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{modelName}} " }
   ]
  },
  {
   "title": "Proxmox RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prox" }
     ]
    }
   ]
  },
  {
   "title": "Proxmox CPU",
   "type": "gauge",
   "description": "Proxmox CPU Usage",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "prox" }
     ]
    }
   ]
  },
  {
   "title": "ZPool Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_nread{zpool=~\"anime|hentai|pxbackup\"}[1m]) /1024 /1024",
     "legendFormat": "{{zpool}} read "
    },
    {
     "expr": "irate(node_zfs_zpool_nwritten{zpool=~\"anime|hentai|pxbackup\"}[1m]) /1024 /1024",
     "legendFormat": "{{zpool}} write"
    }
   ]
  },
  {
   "title": "Plex GPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_ENC_UTIL", "legendFormat": "{{modelName}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m]) * 8",
     "legendFormat": "{{device}} -  Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])*8 ",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  }
 ]
}